src/Entity/Movie.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 */
class Movie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le titre est obligatoire")
     */
    private $title;
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="L'affiche est obligatoire")
     * @Assert\Url
     */
    private $poster;
    /**
     * @ORM\Column(type="datetime")
     */
    private $releaseAt;
    /**
     * @ORM\Column(type="text")
     */
    private $synopsis;
    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="movies")
     * @Assert\NotBlank(message="Le résumé est obligatoire")
     */
    private $categories;
    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\People", mappedBy="actedIn")
     * @Assert\NotBlank(message="Les acteurs sont obligatoires")
     * @Assert\Count(min=1, minMessage="Sélectionner au moins un acteur ou actrice")
     */
    private $actors;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\People", inversedBy="directed")
     * @Assert\NotBlank(message="Le réalisateur ou réalisatrice est obligatoire")
     */
    private $director;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Rating", mappedBy="movie", orphanRemoval=true)
     */
    private $ratings;
    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->actors = new ArrayCollection();
        $this->ratings = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     */
    public function onCreate()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    public function getAverageRating()
    {
        if ($this->ratings->count() == 0) {
            return 0;
        }

        $total = 0;

        foreach ($this->ratings as $rating) {
            $total += $rating->getNotation();
        }

        $average = round($total / $this->ratings->count(), 1);

        return $average;
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    public function getTitle(): ?string
    {
        return $this->title;
    }
    public function setTitle(string $title): self
    {
        $this->title = $title;
        return $this;
    }
    public function getSlug(): ?string
    {
        return $this->slug;
    }
    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;
        return $this;
    }
    public function getPoster(): ?string
    {
        return $this->poster;
    }
    public function setPoster(string $poster): self
    {
        $this->poster = $poster;
        return $this;
    }
    public function getReleaseAt(): ?\DateTimeInterface
    {
        return $this->releaseAt;
    }
    public function setReleaseAt(\DateTimeInterface $releaseAt): self
    {
        $this->releaseAt = $releaseAt;
        return $this;
    }
    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }
    public function setSynopsis(string $synopsis): self
    {
        $this->synopsis = $synopsis;
        return $this;
    }
    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }
    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }
        return $this;
    }
    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
        }
        return $this;
    }
    /**
     * @return Collection|People[]
     */
    public function getActors(): Collection
    {
        return $this->actors;
    }
    public function addActor(People $actor): self
    {
        if (!$this->actors->contains($actor)) {
            $this->actors[] = $actor;
            $actor->addActedIn($this);
        }
        return $this;
    }
    public function removeActor(People $actor): self
    {
        if ($this->actors->contains($actor)) {
            $this->actors->removeElement($actor);
            $actor->removeActedIn($this);
        }
        return $this;
    }
    public function getDirector(): ?People
    {
        return $this->director;
    }
    public function setDirector(?People $director): self
    {
        $this->director = $director;
        return $this;
    }
    /**
     * @return Collection|Rating[]
     */
    public function getRatings(): Collection
    {
        return $this->ratings;
    }
    public function addRating(Rating $rating): self
    {
        if (!$this->ratings->contains($rating)) {
            $this->ratings[] = $rating;
            $rating->setMovie($this);
        }
        return $this;
    }
    public function removeRating(Rating $rating): self
    {
        if ($this->ratings->contains($rating)) {
            $this->ratings->removeElement($rating);
            // set the owning side to null (unless already changed)
            if ($rating->getMovie() === $this) {
                $rating->setMovie(null);
            }
        }
        return $this;
    }
}

src/Entity/People.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PeopleRepository")
 */
class People
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;
    /**
     * @ORM\Column(type="text")
     */
    private $description;
    /**
     * @ORM\Column(type="datetime")
     */
    private $birthday;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $picture;
    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Movie", inversedBy="actors")
     */
    private $actedIn;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Movie", mappedBy="director")
     */
    private $directed;
    public function __construct()
    {
        $this->actedIn = new ArrayCollection();
        $this->directed = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     */
    public function onCreate()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName, $this->lastName);
        }
    }

    public function getFullName()
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }
    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;
        return $this;
    }
    public function getLastName(): ?string
    {
        return $this->lastName;
    }
    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;
        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }
    public function setSlug(string $slug): self
    {
        $this->slug = $slug;
        return $this;
    }
    public function getDescription(): ?string
    {
        return $this->description;
    }
    public function setDescription(string $description): self
    {
        $this->description = $description;
        return $this;
    }
    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }
    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;
        return $this;
    }
    public function getPicture(): ?string
    {
        return $this->picture;
    }
    public function setPicture(string $picture): self
    {
        $this->picture = $picture;
        return $this;
    }
    /**
     * @return Collection|Movie[]
     */
    public function getActedIn(): Collection
    {
        return $this->actedIn;
    }
    public function addActedIn(Movie $actedIn): self
    {
        if (!$this->actedIn->contains($actedIn)) {
            $this->actedIn[] = $actedIn;
        }
        return $this;
    }
    public function removeActedIn(Movie $actedIn): self
    {
        if ($this->actedIn->contains($actedIn)) {
            $this->actedIn->removeElement($actedIn);
        }
        return $this;
    }
    /**
     * @return Collection|Movie[]
     */
    public function getDirected(): Collection
    {
        return $this->directed;
    }
    public function addDirected(Movie $directed): self
    {
        if (!$this->directed->contains($directed)) {
            $this->directed[] = $directed;
            $directed->setDirector($this);
        }
        return $this;
    }
    public function removeDirected(Movie $directed): self
    {
        if ($this->directed->contains($directed)) {
            $this->directed->removeElement($directed);
            // set the owning side to null (unless already changed)
            if ($directed->getDirector() === $this) {
                $directed->setDirector(null);
            }
        }
        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Repository\MovieRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(MovieRepository $repo)
    {
        return $this->render('default/index.html.twig', [
            'lastReleased' => $repo->findLastReleasedMovies(),
            'bestMovies' => $repo->findBestMoviesByAvgRatings(),
            'worstMovies' => $repo->findWorstMoviesByAvgRatings()
        ]);
    }
}

templates/default/_stats.html.twig
<div class="row">
    {% for movie in movies %}
        <div class="col-4 mb-3">
            <div class="card">
                <img src="{{movie.poster}}" class="img-fluid" alt="">
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="{{path('show_movie', {'slug': movie.slug})}}">
                            {{movie.title}}
                        </a>

                    </h4>
                    {% for category in movie.categories %}
                        <a href="{{path('show_category', {'slug': category.slug})}}" class="badge badge-dark">
                            {{ category.title }}
                        </a>
                    {% endfor %}
                    <hr>

                    <div class="d-flex justify-content-between align-items-center">
                        <h4>
                            {% if movie.averageRating > 2.5 %}
                                {% set className = "badge-success" %}
                            {% elseif movie.averageRating > 1.5 %}
                                {% set className = "badge-warning" %}
                            {% else %}
                                {% set className = "badge-danger" %}
                            {% endif %}
                            <span class="badge {{className}}">
                                Noté :
                                {{ movie.averageRating | number_format(2, ",", " ") }}
                                / 5
                            </span>
                        </h4>
                        <h6 class="card-subtitle text-muted">Critiqué par
                            {{movie.ratings|length}}
                            utilisateurs</h6>
                    </div>

                    <hr>

                    <p class="card-text">
                        <strong>Réalisé par :
                        </strong>
                        <a href="{{ path('people', {'slug': movie.director.slug}) }}">{{movie.director.fullName}}</a>

                        <br>
                        <strong>Sorti en :
                        </strong>
                        {{ movie.releaseAt | date('Y') }}
                        <br>
                        {# <strong>Avec :
                                                                        </strong>
                                                                        {% for actor in movie.someActors(3) %}
                                                                            {% if not loop.last %}
                                                                                {{ actor.fullName }},
                                                                            {% else %}
                                                                                {{ actor.fullName}}
                                                                            {% endif %}
                                                                        {% endfor %}
                                                
                                                                        {% if movie.actors|length > 3 %}
                                                                            et
                                                                            {{movie.actors|length - 3}}
                                                                            autres acteurs
                                                                        {% endif %} #}
                    </p>

                    <p class="card-text">{{movie.synopsis}}</p>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil
{% endblock %}

{% block body %}
    <h2>Dernières sorties</h2>
    {% include "default/_stats.html.twig" with {'movies': lastReleased} %}

    <h2>Les meilleurs films selon les utilisateurs</h2>
    {% include "default/_stats.html.twig" with {'movies': bestMovies} %}

    <h2>Les pires films selon les utilisateurs</h2>
    {% include "default/_stats.html.twig" with {'movies': worstMovies} %}

{% endblock %}